project_id = "xoorrglcphuanqatbshg"

[functions.send-newsletter]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.notify-order]
verify_jwt = false

[functions.send-to-courier]
verify_jwt = false