project_id = "xoorrglcphuanqatbshg"

[functions.send-newsletter]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.notify-order]
verify_jwt = false

[functions.send-to-courier]
verify_jwt = false

[functions.check-courier-status]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false