import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import {
  BYLINE_LAYOUT_CLASS,
  bylineClass,
  CARD_TITLE_CLASS,
  CARD_DESCRIPTION_CLASS,
} from "@/lib/cardStyles";
import Byline from "@/components/Byline";
import FeaturedCardSkeleton from "@/components/FeaturedCardSkeleton";
import ProductCardSkeleton from "@/components/ProductCardSkeleton";
import CourseCard, { type CourseCardCourse } from "@/components/cards/CourseCard";
import BookCard, { type BookCardBook } from "@/components/cards/BookCard";
import snapshot from "./__snapshots__/cardStyleTokens.json";

/**
 * Visual-regression guard for card height shifts between loading and loaded states.
 *
 * The instructor/author byline reserves a fixed min-height at every breakpoint.
 * If a skeleton or card stops sharing the BYLINE_LAYOUT_CLASS tokens, the card
 * will visibly jump on data load — these assertions fail before that ships.
 */

/**
 * Expected tokens come from the snapshot regenerated by
 *   bun run scripts/update-card-style-snapshots.mjs --write
 * (gated behind --write). This keeps the contract in one place: edit
 * src/lib/cardStyles.ts → run the script → tests pass with the new values.
 */
const MIN_H_TOKENS = snapshot.BYLINE_LAYOUT_CLASS.minHeight;
const LEADING_TOKENS = snapshot.BYLINE_LAYOUT_CLASS.leading;

const TITLE_MIN_H_TOKENS = snapshot.CARD_TITLE_CLASS.minHeight;
const TITLE_CLAMP_TOKEN = snapshot.CARD_TITLE_CLASS.clamp[0];

const DESC_MIN_H_TOKENS = snapshot.CARD_DESCRIPTION_CLASS.minHeight;
const DESC_CLAMP_TOKEN = snapshot.CARD_DESCRIPTION_CLASS.clamp[0];

const TITLE_SKELETON_TOKEN = snapshot.SKELETON.titleBar;
const PRICE_SKELETON_TOKEN = snapshot.SKELETON.priceBar;

/**
 * Split a className string (or arbitrary HTML blob) into the discrete
 * Tailwind class tokens it contains. We tokenize on whitespace and on the
 * HTML attribute boundaries (`"`, `'`, `\``) so the same helper works both
 * for direct `element.className` strings AND for `container.innerHTML`
 * blobs that wrap class lists in attribute quotes.
 */
const tokenize = (input: string): Set<string> => {
  const out = new Set<string>();
  for (const piece of input.split(/[\s"'`<>=]+/)) {
    if (piece) out.add(piece);
  }
  return out;
};

/**
 * Assert every expected token is present in `cls` as an exact class token.
 * Substring matching is unsafe for breakpoint-prefixed tokens — e.g.
 * `"sm:min-h-[2.5rem]".includes("min-h-[2.5rem]")` is true, which would let
 * a regression that drops the base variant slip through. By tokenizing on
 * whitespace we require `sm:` / `md:` / `lg:` prefixes to match exactly.
 *
 * Failure format is preserved (see scripts/card-layout-summary.mjs).
 */
const expectAllTokens = (cls: string, tokens: string[], source = "class string") => {
  const present = tokenize(cls);
  // Collect every missing token before throwing so the CI summary lists
  // ALL drifts at once instead of one-per-rerun.
  const missing = tokens.filter((t) => !present.has(t));
  if (missing.length === 0) return;
  const blocks = missing
    .map(
      (t) =>
        `TOKEN_MISMATCH source="${source}" token="${t}"\n` +
        `expected: ${t}\n` +
        `actual:   ${cls}`,
    )
    .join("\n---\n");
  throw new Error(blocks);
};

const expectContainsToken = (haystack: string, token: string, source: string) => {
  if (!tokenize(haystack).has(token)) {
    throw new Error(
      `TOKEN_MISMATCH source="${source}" token="${token}"\n` +
        `expected: ${token}\n` +
        `actual:   <not present in ${source}>`,
    );
  }
};

describe("card layout stability — byline tokens", () => {
  it("BYLINE_LAYOUT_CLASS reserves identical min-heights at every breakpoint", () => {
    expectAllTokens(BYLINE_LAYOUT_CLASS, MIN_H_TOKENS, "BYLINE_LAYOUT_CLASS");
    expectAllTokens(BYLINE_LAYOUT_CLASS, LEADING_TOKENS, "BYLINE_LAYOUT_CLASS");
  });

  it("bylineClass() output (cards) contains the shared layout tokens", () => {
    const filled = bylineClass("Some Author");
    const empty = bylineClass("");
    expectAllTokens(filled, MIN_H_TOKENS, "bylineClass(filled)");
    expectAllTokens(empty, MIN_H_TOKENS, "bylineClass(empty)");
  });

  it("<Byline> renders a <p> using the shared layout tokens", () => {
    const { container } = render(<Byline value="Engr. Test" emptyText="Fallback" />);
    const p = container.querySelector("p")!;
    expect(p).not.toBeNull();
    expectAllTokens(p.className, MIN_H_TOKENS, "<Byline> <p>.className");
  });

  it("FeaturedCardSkeleton byline placeholder uses the same min-height tokens", () => {
    const { container } = render(<FeaturedCardSkeleton aspect="video" />);
    const html = container.innerHTML;
    expectAllTokens(html, MIN_H_TOKENS, "FeaturedCardSkeleton.innerHTML");
  });

  it("ProductCardSkeleton byline placeholder uses the same min-height tokens", () => {
    const { container } = render(<ProductCardSkeleton count={1} />);
    const html = container.innerHTML;
    expectAllTokens(html, MIN_H_TOKENS, "ProductCardSkeleton.innerHTML");
  });
});

describe("card layout stability — title tokens", () => {
  it("CARD_TITLE_CLASS reserves min-heights and clamps to 2 lines", () => {
    expectAllTokens(CARD_TITLE_CLASS, TITLE_MIN_H_TOKENS, "CARD_TITLE_CLASS");
    expectContainsToken(CARD_TITLE_CLASS, TITLE_CLAMP_TOKEN, "CARD_TITLE_CLASS");
  });

  it("CourseCard featured renders <h3> with CARD_TITLE_CLASS tokens", () => {
    const course: CourseCardCourse = {
      id: "c1",
      title: "Test Course",
      slug: "test",
      instructor: "Engr. T",
      price: 100,
      original_price: 200,
      image_url: "",
      category: "Cat",
      duration: "1h",
    };
    const { container } = render(
      <MemoryRouter>
        <CourseCard course={course} variant="featured" cta={{ text: "Buy", tone: "primary" }} />
      </MemoryRouter>,
    );
    const h3 = container.querySelector("h3")!;
    expect(h3).not.toBeNull();
    expectAllTokens(h3.className, TITLE_MIN_H_TOKENS, "CourseCard <h3>.className");
    expectContainsToken(h3.className, TITLE_CLAMP_TOKEN, "CourseCard <h3>.className");
  });

  it("BookCard featured renders <h3> with CARD_TITLE_CLASS tokens", () => {
    const book: BookCardBook = {
      id: "b1",
      title: "Test Book",
      slug: "test",
      author: "Author",
      price: 100,
      original_price: 150,
      image_url: "",
      category: "Cat",
      book_type: "physical",
    };
    const { container } = render(
      <MemoryRouter>
        <BookCard book={book} variant="featured" cta={{ text: "Buy", tone: "primary" }} />
      </MemoryRouter>,
    );
    const h3 = container.querySelector("h3")!;
    expect(h3).not.toBeNull();
    expectAllTokens(h3.className, TITLE_MIN_H_TOKENS, "BookCard <h3>.className");
    expectContainsToken(h3.className, TITLE_CLAMP_TOKEN, "BookCard <h3>.className");
  });

  it("Skeletons reserve a title bar of identical width to the card title row", () => {
    const featured = render(<FeaturedCardSkeleton aspect="video" />).container.innerHTML;
    const product = render(<ProductCardSkeleton count={1} />).container.innerHTML;
    expectContainsToken(featured, TITLE_SKELETON_TOKEN, "FeaturedCardSkeleton.innerHTML");
    expectContainsToken(product, TITLE_SKELETON_TOKEN, "ProductCardSkeleton.innerHTML");
  });
});

describe("card layout stability — description tokens", () => {
  it("CARD_DESCRIPTION_CLASS reserves min-heights and clamps to 2 lines", () => {
    expectAllTokens(CARD_DESCRIPTION_CLASS, DESC_MIN_H_TOKENS, "CARD_DESCRIPTION_CLASS");
    expectContainsToken(CARD_DESCRIPTION_CLASS, DESC_CLAMP_TOKEN, "CARD_DESCRIPTION_CLASS");
  });

  it("CourseCard renders description preview with CARD_DESCRIPTION_CLASS tokens", () => {
    const course: CourseCardCourse = {
      id: "c1",
      title: "T",
      slug: "t",
      instructor: "I",
      price: 100,
      original_price: null,
      image_url: "",
      category: "C",
      duration: "1h",
    };
    const { container } = render(
      <MemoryRouter>
        <CourseCard
          course={course}
          variant="featured"
          cta={{ text: "Buy", tone: "primary" }}
          descriptionPreview="Some preview text"
        />
      </MemoryRouter>,
    );
    const desc = Array.from(container.querySelectorAll("p")).find((p) =>
      p.textContent?.includes("Some preview text"),
    )!;
    expect(desc).toBeTruthy();
    expectAllTokens(desc.className, DESC_MIN_H_TOKENS, "CourseCard description <p>.className");
    expectContainsToken(desc.className, DESC_CLAMP_TOKEN, "CourseCard description <p>.className");
  });
});

describe("card layout stability — pricing row", () => {
  it("FeaturedCardSkeleton reserves a price bar matching the card price row", () => {
    const html = render(<FeaturedCardSkeleton aspect="video" />).container.innerHTML;
    expectContainsToken(html, PRICE_SKELETON_TOKEN, "FeaturedCardSkeleton.innerHTML");
  });

  it("ProductCardSkeleton reserves a price bar matching the card price row", () => {
    const html = render(<ProductCardSkeleton count={1} />).container.innerHTML;
    expectContainsToken(html, PRICE_SKELETON_TOKEN, "ProductCardSkeleton.innerHTML");
  });
});
